/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package azzamproyekdb01;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Guest OSN
 */
public class EmployeeTableInterface extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeTableInterface
     */
    public EmployeeTableInterface() {
        initComponents();
        loadEmployees();
    }
    
    private Long employee_id;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();
        btnDataEdit = new javax.swing.JButton();
        btnMenuReturn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAccessManager = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "ID", "Nama", "Posisi", "Alamat", "Email", "No Telp."
            }
        ));
        jScrollPane1.setViewportView(tblEmployee);

        btnDataEdit.setText("Ubah Data");
        btnDataEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataEditActionPerformed(evt);
            }
        });

        btnMenuReturn.setText("Kembali ke Menu");
        btnMenuReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuReturnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("TABEL DATA KARYAWAN");

        btnAccessManager.setText("Cek Daftar Manajer");
        btnAccessManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccessManagerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDataEdit)
                    .addComponent(btnMenuReturn)
                    .addComponent(btnAccessManager))
                .addGap(0, 8, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDataEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAccessManager)
                        .addGap(18, 18, 18)
                        .addComponent(btnMenuReturn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDataEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataEditActionPerformed
        // TODO add your handling code here:
        EmployeeDataInput dataInputFrame=new EmployeeDataInput();
        
        dataInputFrame.setVisible(true);
    }//GEN-LAST:event_btnDataEditActionPerformed

    private void btnMenuReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuReturnActionPerformed
        // TODO add your handling code here:
        AdminMenu admMenu=new AdminMenu();
        
        admMenu.setVisible(true);
        EmployeeTableInterface.this.setVisible(false);
    }//GEN-LAST:event_btnMenuReturnActionPerformed

    private void btnAccessManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccessManagerActionPerformed
        // TODO add your handling code here:
        ManagerTableInterface manTable=new ManagerTableInterface();
        
        manTable.setVisible(true);
        EmployeeTableInterface.this.setVisible(false);
    }//GEN-LAST:event_btnAccessManagerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeTableInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeTableInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeTableInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeTableInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeTableInterface().setVisible(true);
            }
        });
    }
    
    void loadEmployees(){
    // Tidak perlu memeriksa employee_id jika ingin memuat semua data
    DefaultTableModel tableModel = (DefaultTableModel) tblEmployee.getModel();
    tableModel.setRowCount(0);  // Bersihkan tabel sebelum memuat data baru

    String query = "SELECT employee_id, name, position, address, email, phone FROM EmployeeList";

    try (Connection conn = DBConnection.getConnection();
         PreparedStatement pstmt = conn.prepareStatement(query);
         ResultSet rs = pstmt.executeQuery()) {
        
        while(rs.next()){
            long employee_id = rs.getLong("employee_id");
            String employee_name = rs.getString("name");
            String position = rs.getString("position");
            String address = rs.getString("address");
            String email = rs.getString("email");
            String phone = rs.getString("phone");
            
            // Tambahkan data ke tabel
            Object[] row = {employee_id, employee_name, position, address, email, phone};
            tableModel.addRow(row);
        }
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error saat memuat data karyawan: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccessManager;
    private javax.swing.JButton btnDataEdit;
    private javax.swing.JButton btnMenuReturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmployee;
    // End of variables declaration//GEN-END:variables
}
